### ISSUE TITLE
hydra patters twitter feed not working

### ISSUE THREAD

**Issue by hellocatfood** [hydra-synth/hydra#201]
Pressing the share/upload button on the hydra website doesn't share the sketch to the hydra patterns twitter feed. That twitter feed hasn't been updated since 2021 https://twitter.com/hydra_patterns

**Comment by ritchse** [comment]
Hi Antonio! There are currently no plans to fix the Twitter feed since the bot is constantly marked by Twitter as spam. Probably because of the images and how it can tag other people. But there are plans to make an independent hydra gallery in the future! The database is still working tho so you can still use the feature to generate unique URLs and the same sketches on the database will be present in the future hydra gallery.

**Comment by ojack** [comment]
I am currently in contact with twitter but so far no response :/ :/ Either way still want to keep working on alternative gallery

**Comment by ojack** [comment]
Working now!
